#if defined(DERPLIB_USING_COMMON_MACROS)

#undef DERPLIB_NODISCARD
#undef DERPLIB_CPP11_CONSTEXPR
#undef DERPLIB_CPP14_CONSTEXPR
#undef DERPLIB_MAYBE_UNUSED
#undef DERPLIB_NOEXCEPT

#undef DERPLIB_USING_COMMON_MACROS
#endif  // defined(DERPLIB_USING_COMMON_MACROS)
